# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  common.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class RunvaultSharedDefinitions(RootModel[Any]):
    root: Any = Field(..., title='runvault shared definitions')


class Slug(RootModel[constr(pattern=r'^[a-z0-9][a-z0-9._-]{0,63}$')]):
    root: constr(pattern=r'^[a-z0-9][a-z0-9._-]{0,63}$') = Field(
        ...,
        description='パス要素になりうる識別子. NFC 正規化済みの小文字英数字と . _ - のみ. 64 文字以内',
    )


class RunUid(RootModel[constr(pattern=r'^[0-7][0-9A-HJKMNP-TV-Z]{25}$')]):
    root: constr(pattern=r'^[0-7][0-9A-HJKMNP-TV-Z]{25}$') = Field(
        ...,
        description='ULID. 先頭文字は 0-7 (48bit の時刻部が 26 文字に収まる範囲). 全ファイル・全索引の主キー',
    )


class RunSlug(
    RootModel[
        constr(
            pattern=r'^[a-z0-9][a-z0-9._-]{0,63}_[0-9]{8}_[0-9]{6}_[0-9a-f]{8}_[0-9a-f]{4}(-[0-9]+)?$'
        )
    ]
):
    root: constr(
        pattern=r'^[a-z0-9][a-z0-9._-]{0,63}_[0-9]{8}_[0-9]{6}_[0-9a-f]{8}_[0-9a-f]{4}(-[0-9]+)?$'
    ) = Field(..., description='ディレクトリ名. 人間向けであり一意性は保証しない')


class Algorithm(Enum):
    blake3 = 'blake3'
    sha256 = 'sha256'


class Hash(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    algorithm: Algorithm
    value: constr(pattern=r'^[0-9a-f]{64}$')


class DigestHex(RootModel[constr(pattern=r'^[0-9a-f]{64}$')]):
    root: constr(pattern=r'^[0-9a-f]{64}$')


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime


class JsonPointer(RootModel[constr(pattern=r'^(/[^/~]*(~[01][^/~]*)*)+$')]):
    root: constr(pattern=r'^(/[^/~]*(~[01][^/~]*)*)+$')


class Nonempty(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Relpath(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!/)(?!.*(^|/)\.\.(/|$)).+$', min_length=1) = Field(
        ...,
        description='run ディレクトリからの相対パス. 先頭の / と .. を含むパスを禁じる',
    )


class WorkId(
    RootModel[
        constr(
            pattern=r'^(doi:10\.[0-9]{4,9}/\S+|arxiv:[0-9]{4}\.[0-9]{4,5}(v[0-9]+)?|paperid:P[0-9]{8})$'
        )
    ]
):
    root: constr(
        pattern=r'^(doi:10\.[0-9]{4,9}/\S+|arxiv:[0-9]{4}\.[0-9]{4,5}(v[0-9]+)?|paperid:P[0-9]{8})$'
    ) = Field(
        ...,
        description='論文の正規化識別子. doi: / arxiv: / paperid: のいずれかの接頭辞を持つ',
    )
