# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  config.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import common


class Determinism(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    invariant_to: list[common.JsonPointer] | None = Field(
        None,
        description='結果を変えないと実験側が宣言したキー. これだけが条件付き除外の対象',
    )


class Runvault(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hash_exclude: list[common.JsonPointer] | None = Field(
        None, description='/parameters を基点とした JSON Pointer'
    )
    seed_pointers: list[common.JsonPointer] | None = Field(
        None,
        description='乱数シードの所在. config_hash からは除き execution_hash には含める',
    )
    determinism: Determinism | None = None
    sync_include: list[str] | None = None
    sync_exclude: list[str] | None = None


class RunvaultConfigEnvelope(BaseModel):
    """
    ハッシュ対象は /parameters のみ. run ごとに変わる run_uid と制御用の runvault ブロックを /parameters と同じ階層に混ぜないためのエンベロープ
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    run_uid: common.RunUid
    runvault: Runvault
    parameters: dict[str, Any] = Field(
        ..., description='実験条件. 中身は分野ごとに自由'
    )
