# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  event.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, confloat, constr

from . import common


class RunvaultEventRecord(BaseModel):
    schema_: constr(
        pattern=r'^(observation|terminal|note|x\.[a-z0-9][a-z0-9._-]{0,63}\.[a-z0-9][a-z0-9._-]{0,63})$'
    ) = Field(
        ...,
        alias='schema',
        description='コア語彙 (observation / terminal / note) か, 実験固有の x.<repo_id>.<name>',
    )
    run_uid: common.RunUid
    ts: common.Timestamp
    unit_id: constr(min_length=1) | None = Field(None, description='予約語: 観測の主体')
    t: confloat(ge=0.0) | None = Field(None, description='予約語: 主体ごとの経過')
    t_unit: common.Slug | None = Field(None, description='予約語: t の単位')
    outcome: constr(min_length=1) | None = Field(
        None, description='予約語: 終端での結果'
    )
    censored: bool | None = Field(None, description='予約語: 右側打ち切りか')
    budget: confloat(ge=0.0) | None = Field(None, description='予約語: 打ち切り閾値')


class SurvivalObservation(RunvaultEventRecord):
    """
    profile: schema=observation を明示的に要求する
    """

    schema_: Literal['observation'] = Field(
        ...,
        alias='schema',
        description='コア語彙 (observation / terminal / note) か, 実験固有の x.<repo_id>.<name>',
    )
    run_uid: common.RunUid
    ts: common.Timestamp
    unit_id: constr(min_length=1) = Field(..., description='予約語: 観測の主体')
    t: confloat(ge=0.0) = Field(..., description='予約語: 主体ごとの経過')
    t_unit: common.Slug = Field(..., description='予約語: t の単位')


class SurvivalTerminal(RunvaultEventRecord):
    """
    profile: schema=terminal を明示的に要求する
    """

    schema_: Literal['terminal'] = Field(
        ...,
        alias='schema',
        description='コア語彙 (observation / terminal / note) か, 実験固有の x.<repo_id>.<name>',
    )
    budget: confloat(ge=0.0) = Field(..., description='予約語: 打ち切り閾値')
    run_uid: common.RunUid
    ts: common.Timestamp
    unit_id: constr(min_length=1) = Field(..., description='予約語: 観測の主体')
    t: confloat(ge=0.0) = Field(..., description='予約語: 主体ごとの経過')
    t_unit: common.Slug = Field(..., description='予約語: t の単位')
    outcome: constr(min_length=1) = Field(..., description='予約語: 終端での結果')
    censored: bool = Field(..., description='予約語: 右側打ち切りか')
