# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  manifest.row.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, conint

from . import common


class Algorithm(Enum):
    blake3 = 'blake3'
    sha256 = 'sha256'


class ManifestCsvRow(BaseModel):
    """
    finish() が artifacts/ と logs/ を走査して書く. 同期の有無は持たない (集約先から導出する)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_uid: common.RunUid
    path: common.Relpath
    algorithm: Algorithm
    digest: common.DigestHex
    bytes: conint(ge=0)
