# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  metrics.row.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint

from . import common


class MetricsCsvRow(BaseModel):
    """
    CSV は UTF-8 (BOM なし). 欠損は空文字のみ (NA/NaN/null と書かない). 主キーは (run_uid, name, step, step_unit, scope)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_uid: common.RunUid
    step: conint(ge=0) | None = Field(..., description='時系列でない指標では空')
    step_unit: common.Slug | None
    scope: common.Slug = Field(
        ..., description='値の集約粒度: run / trial / agent / flow など'
    )
    name: common.Slug
    value: float = Field(..., description='NaN / Inf は書かない. 欠測は行を書かない')
