# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  reference.row.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint

from . import common


class ReferenceCsvRow(BaseModel):
    """
    論文の報告値. metrics.csv の列に target_id と source を足したもの. 再現実験の run にだけ存在する
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    run_uid: common.RunUid
    step: conint(ge=0) | None
    step_unit: common.Slug | None
    scope: common.Slug
    name: common.Slug
    value: float
    target_id: common.Slug = Field(
        ..., description='research.targets[].target_id を指す'
    )
    source: common.Nonempty = Field(..., description='値の出典 (Table 3 row 2 など)')
