# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  run.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from . import common


class Origin(Enum):
    code = 'code'
    manual = 'manual'
    external = 'external'


class Visibility(Enum):
    internal = 'internal'
    public = 'public'


class Kind(Enum):
    cargo = 'cargo'
    uv = 'uv'
    poetry = 'poetry'
    pip = 'pip'
    other = 'other'


class Lock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    hash: common.Hash
    file: common.Relpath


class Code(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    git_remote: str | None = None
    git_branch: str | None = None
    git_commit: constr(pattern=r'^[0-9a-f]{40}$')
    git_dirty: bool
    dirty_hash: common.Hash | None = Field(
        None,
        description='git_dirty=true のとき, 作業ツリーの差分 (git diff HEAD) のハッシュ',
    )
    repo_relpath: str | None = None
    locks: list[Lock] | None = Field(
        None, description='同梱したロックファイル. 実体は run 直下の lock/ に置く'
    )


class Env(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    env_hash: common.DigestHex
    host: common.Nonempty
    os: common.Nonempty
    arch: common.Nonempty
    rustc_version: str | None = None
    python_version: str | None = None


class Rng(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    master_seed: conint(ge=0) | None = None
    replicate_index: conint(ge=0) | None = None


class Llm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    provider: common.Nonempty
    model_snapshot: common.Nonempty
    temperature: confloat(ge=0.0) | None = None
    system_prompt_hash: common.Hash | None = None


class HashScope(Enum):
    """
    dir_manifest = パス昇順の (相対パス, 内容ハッシュ) 列をハッシュしたもの
    """

    file = 'file'
    dir_manifest = 'dir_manifest'
    NoneType_None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: common.Slug
    name: common.Slug
    dataset_id: constr(min_length=1) | None = Field(None, description='版を含む安定 ID')
    version: constr(min_length=1) | None = None
    hash: common.Hash | None
    hash_scope: HashScope | None = Field(
        None,
        description='dir_manifest = パス昇順の (相対パス, 内容ハッシュ) 列をハッシュしたもの',
    )
    n: conint(ge=0) | None = None
    uri: constr(min_length=1) | None = None
    split: constr(min_length=1) | None = None


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: common.Slug
    name: common.Slug
    dataset_id: constr(min_length=1) = Field(..., description='版を含む安定 ID')
    version: constr(min_length=1) | None = None
    hash: common.Hash | None = None
    hash_scope: HashScope | None = Field(
        None,
        description='dir_manifest = パス昇順の (相対パス, 内容ハッシュ) 列をハッシュしたもの',
    )
    n: conint(ge=0) | None = None
    uri: constr(min_length=1) | None = None
    split: constr(min_length=1) | None = None


class Data2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: common.Slug
    name: common.Slug
    dataset_id: constr(min_length=1) | None = Field(None, description='版を含む安定 ID')
    version: constr(min_length=1) | None = None
    hash: common.Hash | None = None
    hash_scope: HashScope | None = Field(
        None,
        description='dir_manifest = パス昇順の (相対パス, 内容ハッシュ) 列をハッシュしたもの',
    )
    n: conint(ge=0) | None = None
    uri: constr(min_length=1)
    split: constr(min_length=1) | None = None


class Lineage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sweep_id: common.Slug | None = None
    parent_run_uid: common.RunUid | None = Field(
        None, description='sweep 親 run. sweep_id と対で持つ'
    )
    resumed_from: common.RunUid | None = None
    derived_from: common.RunUid | None = None


class Work(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    work_id: common.WorkId
    doi: constr(min_length=1) | None = None
    arxiv_id: constr(min_length=1) | None = None
    paper_id: constr(pattern=r'^P[0-9]{8}$') | None = None
    title: common.Nonempty
    year: conint(ge=1500, le=2200) | None = None
    source_version: constr(min_length=1) | None = Field(
        None,
        description='arXiv v2 / published / preprint など. 版で数値が変わるため必須',
    )


class Kind1(Enum):
    table = 'table'
    figure = 'figure'
    section = 'section'
    claim = 'claim'


class Target(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_id: common.Slug
    kind: Kind1
    label: common.Nonempty
    panel: constr(min_length=1) | None = None
    row: constr(min_length=1) | None = None
    condition: constr(min_length=1) | None = None


class UpstreamImpl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: common.Nonempty
    commit: constr(min_length=1) | None = None


class Research(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    is_replication: bool
    work: Work | None = None
    targets: list[Target] | None = None
    upstream_impl: UpstreamImpl | None = None
    obsidian_note: constr(min_length=1) | None = None
    jira: list[constr(pattern=r'^MYTASK-[0-9]+$')] | None = None


class RunvaultRunMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    vocab_version: constr(pattern=r'^[0-9]+\.[0-9]+$') = Field(
        ..., description='vocabulary.toml の版'
    )
    runvault_version: constr(min_length=1)
    run_uid: common.RunUid
    run_slug: common.RunSlug
    repo_id: common.Slug
    experiment: common.Slug
    subcommand: common.Slug
    domain: common.Slug
    config_hash: common.DigestHex
    execution_hash: common.DigestHex
    created_at: common.Timestamp
    cli_args: list[str] | None = None
    origin: Origin
    visibility: Visibility
    code: Code | None
    env: Env
    rng: Rng | None = None
    llm: Llm | None = None
    data: list[Data | Data1 | Data2] = Field(
        ...,
        description='使用したデータ. 外部データを使わない run は空配列. 未記入とは区別する. (role, name) は run 内で一意',
    )
    lineage: Lineage | None = None
    research: Research
    ext: dict[str, Any] | None = None
