# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  runs.report.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveFloat,
    confloat,
    conint,
    constr,
)

from . import common


class Experiment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    experiment: common.Slug | None = Field(
        ...,
        description='legacy run が results 直下に置かれていると，どの実験のものか記録に無い．その場合の 1 まとまりが null (実データでは 237 件中 233 件がこれ)',
    )
    repo_id: common.Slug
    n_runs: conint(ge=0)
    n_finished: conint(ge=0)
    last_run_at: common.Timestamp | None
    cost_usd: confloat(ge=0.0) | None = None
    git_remote: str | None = Field(
        None,
        description='そのリポジトリの origin. run.json にしか無いので, legacy run しか持たない実験では null',
    )
    primary_metrics: list[common.Slug] = Field(
        ..., description='一覧に出す指標名. 実験ごとに決まる (§5.4)', max_length=3
    )


class State(Enum):
    """
    legacy run には status.json が無く，どう終わったかが記録に無い．unfinished は «status.json が無い正規の run» を意味するので，そこに混ぜず null にする
    """

    finished = 'finished'
    failed = 'failed'
    unfinished = 'unfinished'
    NoneType_None = None


class Replication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: common.Nonempty
    work_id: common.WorkId | None = None
    targets: list[constr(min_length=1)]
    diff: dict[str, Any] | None = Field(None, description='再現値 - 論文報告値')


class Run(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run_uid: common.RunUid | None = Field(None, description='legacy run では null')
    run_slug: common.RunSlug | None = None
    experiment: common.Slug | None = Field(
        ..., description='legacy では記録に無いことがある'
    )
    subcommand: common.Slug | None = Field(..., description='legacy では不明')
    state: State = Field(
        ...,
        description='legacy run には status.json が無く，どう終わったかが記録に無い．unfinished は «status.json が無い正規の run» を意味するので，そこに混ぜず null にする',
    )
    created_at: common.Timestamp
    duration_sec: confloat(ge=0.0) | None = None
    git_dirty: bool | None
    metrics: dict[str, float]
    replication: Replication | None = None
    obsidian_note: constr(min_length=1) | None = None
    jira: list[constr(pattern=r'^MYTASK-[0-9]+$')] | None = None
    run_key: common.Nonempty = Field(
        ..., description='索引の主キー. legacy は legacy:<repo_id>:<相対パス>'
    )
    repo_id: common.Slug = Field(
        ...,
        description='どのリポジトリの run か. 集約先での置き場 (<集約先>/<repo_id>/…) を引くのに要る',
    )


class Kind(Enum):
    env_split = 'env_split'
    dirty_runs = 'dirty_runs'
    stale_lock = 'stale_lock'
    legacy_runs = 'legacy_runs'


class Warning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    message: common.Nonempty
    config_hash: constr(pattern=r'^[0-9a-f]{64}$') | None = None
    n_run: conint(ge=0) | None = None


class RunsJsonObsidianDashboardPayload(BaseModel):
    """
    runvault report --obsidian が vault に書き出す索引の要約. CLI と Emera コンポーネントの契約
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    vocab_version: constr(pattern=r'^[0-9]+\.[0-9]+$')
    generated_at: common.Timestamp
    freshness_hours: PositiveFloat = Field(
        ..., description='これを超えて古ければ画面に «古い» と出す (既定 24)'
    )
    experiments: list[Experiment]
    runs: list[Run]
    warnings: list[Warning]
