# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  status.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint

from . import common


class State(Enum):
    finished = 'finished'
    failed = 'failed'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: common.Nonempty
    message: common.Nonempty


class Counts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metrics: conint(ge=0) | None = None
    events: conint(ge=0) | None = None
    artifacts: conint(ge=0) | None = None


class RunvaultRunStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    run_uid: common.RunUid
    state: State
    started_at: common.Timestamp
    finished_at: common.Timestamp
    duration_sec: confloat(ge=0.0) = Field(
        ..., description='実行時間の正本. metrics 側に重複して持たせない'
    )
    exit_code: int | None = None
    collision_index: conint(ge=2) | None = None
    error: Error | None = None
    counts: Counts | None = None
