# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  sync.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint

from . import common


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: common.Nonempty
    repo_id: common.Slug
    path: common.Nonempty = Field(..., description='同期元の run ディレクトリ')


class Compression(Enum):
    none = 'none'
    zstd = 'zstd'


class Source1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hash: common.Hash
    bytes: conint(ge=0)


class Stored(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hash: common.Hash
    bytes: conint(ge=0)


class File(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: common.Relpath = Field(..., description='同期元での相対パス')
    stored_path: common.Relpath = Field(..., description='集約先での相対パス')
    compression: Compression
    source: Source1
    stored: Stored


class SyncJsonAggregationReceipt(BaseModel):
    """
    runvault sync が集約先の run ディレクトリに置く受領証. 何をいつどの形で送ったかの正本
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    run_uid: common.RunUid | None = Field(..., description='legacy run では null')
    run_key: common.Nonempty
    generation: conint(ge=1) = Field(
        ..., description='同じ run を何度目に同期したか. 再同期のたびに 1 増える'
    )
    synced_at: common.Timestamp
    verified: bool | None = Field(
        None, description='runvault verify --deep に通ったか. false では同期しない'
    )
    source: Source
    files: list[File] = Field(
        ...,
        description='集約先に置いたファイル. 圧縮したものは stored_path が .zst になる',
    )
