# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  tombstone.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict

from . import common


class State(Enum):
    finished = 'finished'
    failed = 'failed'


class RunvaultDeletionTombstone(BaseModel):
    """
    runvault delete が追記する削除記録．1 行を _deleted.jsonl の 1 レコードとして保存する
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    run_uid: common.RunUid
    repo_id: common.Slug
    experiment: common.Slug
    run_slug: common.RunSlug
    state: State
    deleted_at: common.Timestamp
    host: common.Nonempty
    reason: common.Nonempty
    runvault_version: common.Nonempty
