# Generated from schema/v1 by tools/gen_pydantic.py. Do not edit.
# generated by datamodel-codegen:
#   filename:  vault.config.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, PositiveFloat


class RunvaultVaultTomlAggregationRepositoryDeclaration(BaseModel):
    """
    集約リポジトリのルートに置く宣言. これが無い / 通らない場合 runvault sync は停止する (fail closed)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    visibility: Literal['private'] = Field(
        ..., description='private 以外の値は許さない. public な集約先へは同期しない'
    )
    compress_over_mib: PositiveFloat | None = 10
    allow_internal: bool | None = Field(
        False, description='visibility=internal の run を既定で受け入れるか'
    )
    note: str | None = None
