"""A run that Rust wrote, read back by Python.

`schema/v1/testvectors/` pins the bytes the two implementations hash. It says
nothing about the directory they produce, and it is generated by Python, so on
its own it leaves one direction untested: whether Python agrees with a run Rust
actually wrote. This fixture is that direction.

Regenerate it deliberately, never to make this test pass:

    cargo run -p runvault --example write_fixture
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from runvault.hashes import identity
from runvault.verify import shallow

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "rust_run" / "results"


def _run_dir() -> Path:
    # `latest_finished` sits beside the run and resolves to it, so testing
    # for run.json alone finds the link as well as its target.
    found = sorted(
        d for d in FIXTURES.glob("*/*")
        if not d.is_symlink() and (d / "run.json").is_file()
    )
    if not found:
        pytest.fail(
            f"no fixture under {FIXTURES}; regenerate with "
            "`cargo run -p runvault --example write_fixture`"
        )
    return found[0]


@pytest.fixture(scope="module")
def rust_run() -> Path:
    return _run_dir()


@pytest.fixture(scope="module")
def meta(rust_run: Path) -> dict:
    return json.loads((rust_run / "run.json").read_text(encoding="utf-8"))


def test_python_accepts_a_run_rust_wrote(rust_run: Path) -> None:
    shallow(rust_run)


def test_the_three_hashes_recompute_to_what_rust_recorded(rust_run: Path, meta: dict) -> None:
    config = json.loads((rust_run / "config.json").read_text(encoding="utf-8"))
    env = dict(meta["env"])
    env["locks"] = (meta.get("code") or {}).get("locks", [])

    got = identity(config, meta.get("data") or [], env, meta.get("code"))

    assert got.env_hash == meta["env"]["env_hash"]
    assert got.config_hash == meta["config_hash"]
    assert got.execution_hash == meta["execution_hash"]


def test_the_directory_name_still_carries_the_hashes(rust_run: Path, meta: dict) -> None:
    # The reason the fixture is a directory and not a blob of JSON: the slug is
    # where a reader looks first, and nothing else pins it across the two sides.
    _, _, cfg8, exec4 = rust_run.name.rsplit("_", 3)
    assert meta["config_hash"].startswith(cfg8)
    assert meta["execution_hash"].startswith(exec4)


def test_the_light_half_is_all_present(rust_run: Path) -> None:
    for name in (
        "run.json", "config.json", "status.json",
        "metrics.csv", "reference.csv", "manifest.csv", "events.jsonl",
    ):
        assert (rust_run / name).is_file(), name
